// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2RYGwSOJZ6xTkLtr2K1ErUDyzn7bs5cM',
    appId: '1:126666832937:web:8adc6251dd8793fb053038',
    messagingSenderId: '126666832937',
    projectId: 'vyoma-in',
    authDomain: 'vyoma-in.firebaseapp.com',
    storageBucket: 'vyoma-in.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6I9E_nF-5dx_HaxsJ151ncUC9cflchdE',
    appId: '1:126666832937:android:afa563694c228a29053038',
    messagingSenderId: '126666832937',
    projectId: 'vyoma-in',
    storageBucket: 'vyoma-in.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIR1hqUO6P7dblSPXaXdB7sDXPf_sxM0k',
    appId: '1:126666832937:ios:d9167644211ec3fa053038',
    messagingSenderId: '126666832937',
    projectId: 'vyoma-in',
    storageBucket: 'vyoma-in.firebasestorage.app',
    iosClientId: '126666832937-keuqil3kqmijirdi4te3m3psfe8rt17f.apps.googleusercontent.com',
    iosBundleId: 'com.vyoma.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIR1hqUO6P7dblSPXaXdB7sDXPf_sxM0k',
    appId: '1:126666832937:ios:d9167644211ec3fa053038',
    messagingSenderId: '126666832937',
    projectId: 'vyoma-in',
    storageBucket: 'vyoma-in.firebasestorage.app',
    iosClientId: '126666832937-keuqil3kqmijirdi4te3m3psfe8rt17f.apps.googleusercontent.com',
    iosBundleId: 'com.vyoma.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2RYGwSOJZ6xTkLtr2K1ErUDyzn7bs5cM',
    appId: '1:126666832937:web:9e54063073fbb165053038',
    messagingSenderId: '126666832937',
    projectId: 'vyoma-in',
    authDomain: 'vyoma-in.firebaseapp.com',
    storageBucket: 'vyoma-in.firebasestorage.app',
  );
}
