import 'dart:async';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:googleapis/calendar/v3.dart' as calendar;
import 'models/user_preferences.dart';
import 'calendar_service.dart';
import 'weather_service.dart';
import 'device_service.dart';
import 'window_spy.dart';
import 'memory_service.dart';
import 'ai_service.dart';

/// Alert types that can be triggered by the Sentinel
enum AlertType {
  morningBrief,
  endOfDayReview,
  lateForEvent,
  weatherWarning,
  lowBattery,
  focusDrift,
  awolReturn,
}

/// A proactive alert generated by the Sentinel
class ProactiveAlert {
  final AlertType type;
  final String title;
  final String body;
  final Map<String, dynamic>? data;
  final DateTime timestamp;

  ProactiveAlert({
    required this.type,
    required this.title,
    required this.body,
    this.data,
    DateTime? timestamp,
  }) : timestamp = timestamp ?? DateTime.now();
}

/// SentinelService - Background monitor for proactive intelligence
/// Monitors context (calendar, weather, battery, focus) and triggers smart alerts
class SentinelService extends ChangeNotifier {
  Timer? _patrolTimer;
  final CalendarService _calendar;
  final WeatherService _weather;
  final DeviceService _device;
  final WindowSpy _windowSpy;
  final MemoryService _memory;
  AIService? _aiService; // Set after initialization
  
  UserPreferences _preferences = UserPreferences();
  UserPreferences get preferences => _preferences;
  
  // Track state for drift detection
  String? _lastActiveApp;
  DateTime? _distractionStartTime;
  bool _briefSentToday = false;
  bool _reviewSentToday = false;
  DateTime? _lastPatrolTime;
  
  // Alert callback
  Function(ProactiveAlert)? onAlert;
  
  // Notification plugin
  final FlutterLocalNotificationsPlugin _notifications = FlutterLocalNotificationsPlugin();
  
  SentinelService({
    required CalendarService calendar,
    required WeatherService weather,
    required DeviceService device,
    required WindowSpy windowSpy,
    required MemoryService memory,
  }) : _calendar = calendar,
       _weather = weather,
       _device = device,
       _windowSpy = windowSpy,
       _memory = memory {
    _initNotifications();
    _loadPreferences();
  }

  /// Set the AI service (called after AIService is initialized)
  void setAIService(AIService ai) {
    _aiService = ai;
  }

  /// Initialize local notifications
  Future<void> _initNotifications() async {
    const androidSettings = AndroidInitializationSettings('@mipmap/ic_launcher');
    const darwinSettings = DarwinInitializationSettings(
      requestAlertPermission: true,
      requestBadgePermission: true,
      requestSoundPermission: true,
    );
    
    const initSettings = InitializationSettings(
      android: androidSettings,
      iOS: darwinSettings,
      macOS: darwinSettings,
    );
    
    await _notifications.initialize(
      initSettings,
      onDidReceiveNotificationResponse: (response) {
        // Handle notification tap
        print("SENTINEL: Notification tapped - ${response.payload}");
      },
    );
  }

  /// Load preferences from memory
  Future<void> _loadPreferences() async {
    final prefsJson = _memory.getSegment('sentinel_preferences');
    if (prefsJson != null && prefsJson is Map<String, dynamic>) {
      _preferences = UserPreferences.fromJson(prefsJson);
    }
    notifyListeners();
  }

  /// Save preferences to memory
  Future<void> updatePreferences(UserPreferences newPrefs) async {
    _preferences = newPrefs;
    await _memory.updateSegment('sentinel_preferences', newPrefs.toJson());
    notifyListeners();
  }

  /// Start the background patrol
  void startPatrol({Duration interval = const Duration(minutes: 5)}) {
    _patrolTimer?.cancel();
    _patrolTimer = Timer.periodic(interval, (_) => _patrol());
    print("SENTINEL: Patrol started (every ${interval.inMinutes} min)");
    
    // Run initial patrol
    _patrol();
  }

  /// Stop the background patrol
  void stopPatrol() {
    _patrolTimer?.cancel();
    _patrolTimer = null;
    print("SENTINEL: Patrol stopped");
  }

  /// Main patrol loop - checks all conditions
  Future<void> _patrol() async {
    final now = DateTime.now();
    
    // Check if we're in quiet hours
    if (_preferences.isQuietHours(now)) {
      print("SENTINEL: Quiet hours - skipping patrol");
      return;
    }
    
    print("SENTINEL: Running patrol at ${now.toIso8601String()}");
    
    // Reset daily flags at midnight
    if (_lastPatrolTime != null && _lastPatrolTime!.day != now.day) {
      _briefSentToday = false;
      _reviewSentToday = false;
    }
    _lastPatrolTime = now;
    
    // Check all trigger conditions in parallel
    await Future.wait([
      _checkMorningBrief(now),
      _checkEndOfDayReview(now),
      _checkLateForEvent(now),
      _checkWeatherWarning(now),
      _checkLowBattery(now),
      _checkFocusDrift(now),
    ]);
  }

  /// Check if it's time for morning brief (adaptive: first activity after wake time)
  Future<void> _checkMorningBrief(DateTime now) async {
    if (_briefSentToday) return;
    
    final wakeTime = _parseTime(_preferences.effectiveBriefTime);
    final nowMinutes = now.hour * 60 + now.minute;
    final wakeMinutes = wakeTime.hour * 60 + wakeTime.minute;
    
    // Adaptive: trigger if after wake time (first patrol of the day post-wake)
    // This reaches user when they actually open the app, not at a fixed time
    if (nowMinutes >= wakeMinutes && nowMinutes < wakeMinutes + 180) { // Within 3 hours of wake
      _briefSentToday = true;
      await _triggerMorningBrief();
    }
  }

  /// Check if it's time for end-of-day review
  Future<void> _checkEndOfDayReview(DateTime now) async {
    if (!_preferences.alertEndOfDay || _reviewSentToday) return;
    
    final reviewTime = _parseTime(_preferences.effectiveReviewTime);
    final nowMinutes = now.hour * 60 + now.minute;
    final reviewMinutes = reviewTime.hour * 60 + reviewTime.minute;
    
    if (nowMinutes >= reviewMinutes && nowMinutes <= reviewMinutes + 5) {
      _reviewSentToday = true;
      await _triggerEndOfDayReview();
    }
  }

  /// Check if user is late for an upcoming event
  Future<void> _checkLateForEvent(DateTime now) async {
    if (!_preferences.alertLateForEvent) return;
    
    try {
      final events = await _calendar.syncEvents();
      if (events.isEmpty) return;
      
      for (final event in events) {
        final start = event.start?.dateTime;
        if (start == null) continue;
        
        final minutesUntilEvent = start.difference(now).inMinutes;
        final reminderWindow = _preferences.eventReminderMinutes;
        
        // Check if within reminder window
        if (minutesUntilEvent > 0 && minutesUntilEvent <= reminderWindow) {
          // Don't alert for events we've already alerted about
          final alertKey = 'alerted_${event.id}_${start.toIso8601String()}';
          if (_memory.getFacts().containsKey(alertKey)) continue;
          
          // Mark as alerted
          await _memory.learnFact(alertKey, 'true');
          
          // Clean up after event passes
          Future.delayed(Duration(minutes: minutesUntilEvent + 30), () {
            _memory.forgetFact(alertKey);
          });
          
          await _triggerLateAlert(event, minutesUntilEvent);
          break; // Only one alert per patrol
        }
      }
    } catch (e) {
      print("SENTINEL: Late check error - $e");
    }
  }

  /// Check for weather warnings before outdoor events
  Future<void> _checkWeatherWarning(DateTime now) async {
    if (!_preferences.alertWeatherChange) return;
    
    try {
      final events = await _calendar.syncEvents();
      final weather = await _weather.getWeather();
      
      // Simple check: if weather contains "rain" or "storm" and there's an event soon
      final condition = (weather['condition'] as String?)?.toLowerCase() ?? '';
      final isBadWeather = condition.contains('rain') || 
                           condition.contains('storm') || 
                           condition.contains('snow');
      
      if (!isBadWeather) return;
      
      for (final event in events) {
        final start = event.start?.dateTime;
        if (start == null) continue;
        
        final hoursUntilEvent = start.difference(now).inHours;
        
        // Alert 1-3 hours before event if bad weather
        if (hoursUntilEvent >= 1 && hoursUntilEvent <= 3) {
          final alertKey = 'weather_alerted_${event.id}';
          if (_memory.getFacts().containsKey(alertKey)) continue;
          
          await _memory.learnFact(alertKey, 'true');
          await _triggerWeatherWarning(event, condition);
          break;
        }
      }
    } catch (e) {
      print("SENTINEL: Weather check error - $e");
    }
  }

  /// Check for low battery
  Future<void> _checkLowBattery(DateTime now) async {
    if (!_preferences.alertLowBattery) return;
    
    try {
      final deviceData = await _device.getDeviceStatus();
      final battery = deviceData['battery_level'] as int?;
      
      if (battery == null || battery > _preferences.lowBatteryThreshold) return;
      
      // Don't spam - only alert once per session
      final alertKey = 'battery_alert_${now.day}';
      if (_memory.getFacts().containsKey(alertKey)) return;
      
      // Check if there are upcoming events
      final events = await _calendar.syncEvents();
      final upcomingCount = events.where((e) {
        final start = e.start?.dateTime;
        return start != null && start.difference(now).inHours <= 3;
      }).length;
      
      if (upcomingCount > 0) {
        await _memory.learnFact(alertKey, 'true');
        await _triggerLowBatteryAlert(battery, upcomingCount);
      }
    } catch (e) {
      print("SENTINEL: Battery check error - $e");
    }
  }

  /// Check for focus drift (distraction app open too long)
  Future<void> _checkFocusDrift(DateTime now) async {
    if (!_preferences.alertFocusDrift) return;
    if (!_preferences.isFocusHours(now)) return;
    
    try {
      final windowData = await _windowSpy.spyOnUser();
      final currentApp = windowData['active_app'] as String? ?? '';
      
      if (_preferences.isDistractionApp(currentApp)) {
        if (_lastActiveApp == currentApp && _distractionStartTime != null) {
          final driftMinutes = now.difference(_distractionStartTime!).inMinutes;
          if (driftMinutes >= _preferences.focusDriftThreshold) {
            // Don't spam - reset after alert
            final alertKey = 'drift_alert_${now.hour}';
            if (!_memory.getFacts().containsKey(alertKey)) {
              await _memory.learnFact(alertKey, 'true');
              await _triggerFocusDriftAlert(currentApp, driftMinutes);
            }
          }
        } else {
          // Started new distraction
          _distractionStartTime = now;
        }
      } else {
        // Not on distraction app - reset
        _distractionStartTime = null;
      }
      _lastActiveApp = currentApp;
    } catch (e) {
      print("SENTINEL: Focus drift check error - $e");
    }
  }

  // === TRIGGER METHODS ===

  Future<void> _triggerMorningBrief() async {
    print("SENTINEL: Triggering morning brief");
    
    String briefContent = "Good morning! Here's your day:\n\n";
    
    try {
      // Calendar
      if (_preferences.briefIncludeCalendar) {
        final events = await _calendar.syncEvents();
        briefContent += "📅 ${events.length} events today\n";
        for (final e in events.take(3)) {
          final time = e.start?.dateTime;
          final timeStr = time != null ? "${time.hour}:${time.minute.toString().padLeft(2, '0')}" : "All day";
          briefContent += "  • $timeStr: ${e.summary ?? 'Event'}\n";
        }
      }
      
      // Weather
      if (_preferences.briefIncludeWeather) {
        try {
          final weather = await _weather.getWeather();
          briefContent += "\n☀️ ${weather['condition']} - ${weather['temperature']}°C\n";
        } catch (_) {}
      }
      
      // Goals (from Supermemory)
      if (_preferences.briefIncludeGoals) {
        final protocol = _memory.getSegment('protocol') as Map<String, dynamic>? ?? {};
        final goal = protocol['main_goal'];
        if (goal != null) {
          briefContent += "\n🎯 Today's priority: $goal\n";
        }
      }
      
      // Brief is now template-based only (no AI tokens spent)
    } catch (e) {
      print("SENTINEL: Brief generation error - $e");
    }
    
    await _sendAlert(ProactiveAlert(
      type: AlertType.morningBrief,
      title: "Good Morning ☀️",
      body: briefContent,
    ));
  }

  Future<void> _triggerEndOfDayReview() async {
    print("SENTINEL: Triggering end-of-day review");
    
    // Get metrics from memory
    final metricsJson = _memory.getSegment('productivity_stats');
    String reviewContent = "Here's how today went:\n\n";
    
    if (metricsJson != null) {
      final focusMinutes = metricsJson['focus_minutes'] ?? 0;
      final distractions = metricsJson['distraction_count'] ?? 0;
      final tasks = metricsJson['tasks_completed'] ?? 0;
      
      reviewContent += "⏱️ Focus: ${(focusMinutes / 60).toStringAsFixed(1)} hours\n";
      reviewContent += "⚠️ Distractions: $distractions\n";
      reviewContent += "✅ Tasks: $tasks completed\n";
    }
    
    await _sendAlert(ProactiveAlert(
      type: AlertType.endOfDayReview,
      title: "Day Complete 🌙",
      body: reviewContent,
    ));
  }

  Future<void> _triggerLateAlert(calendar.Event event, int minutesUntil) async {
    final body = "${event.summary ?? 'Event'} starts in $minutesUntil minutes. Time to go!";
    
    await _sendAlert(ProactiveAlert(
      type: AlertType.lateForEvent,
      title: "⏰ Leaving Soon?",
      body: body,
      data: {'event_id': event.id},
    ));
  }

  Future<void> _triggerWeatherWarning(calendar.Event event, String condition) async {
    final body = "Weather alert: $condition expected. ${event.summary ?? 'Your event'} might be affected.";
    
    await _sendAlert(ProactiveAlert(
      type: AlertType.weatherWarning,
      title: "🌧️ Weather Warning",
      body: body,
    ));
  }

  Future<void> _triggerLowBatteryAlert(int battery, int upcomingEvents) async {
    final body = "Battery at $battery%. You have $upcomingEvents event(s) coming up. Consider charging.";
    
    await _sendAlert(ProactiveAlert(
      type: AlertType.lowBattery,
      title: "🔋 Low Battery",
      body: body,
    ));
  }

  Future<void> _triggerFocusDriftAlert(String app, int minutes) async {
    final body = "You've been on $app for $minutes minutes. Time to refocus?";
    
    await _sendAlert(ProactiveAlert(
      type: AlertType.focusDrift,
      title: "🎯 Focus Check",
      body: body,
    ));
  }

  /// Trigger AWOL return alert (called externally by ChronosService)
  Future<void> triggerAwolReturn(int daysAway) async {
    if (!_preferences.alertAwolReturn) return;
    
    await _sendAlert(ProactiveAlert(
      type: AlertType.awolReturn,
      title: "Welcome Back 👋",
      body: "You were away for $daysAway days. Ready to catch up?",
    ));
  }

  /// Send alert via notification and callback
  Future<void> _sendAlert(ProactiveAlert alert) async {
    print("SENTINEL: Sending alert - ${alert.type.name}: ${alert.title}");
    
    // Platform notification
    try {
      await _notifications.show(
        alert.type.index,
        alert.title,
        alert.body,
        NotificationDetails(
          android: AndroidNotificationDetails(
            'sentinel_alerts',
            'Vyoma Alerts',
            channelDescription: 'Proactive intelligence alerts',
            importance: Importance.high,
            priority: Priority.high,
          ),
          iOS: const DarwinNotificationDetails(
            presentAlert: true,
            presentBadge: true,
            presentSound: true,
          ),
          macOS: const DarwinNotificationDetails(
            presentAlert: true,
            presentBadge: true,
            presentSound: true,
          ),
        ),
        payload: alert.type.name,
      );
    } catch (e) {
      print("SENTINEL: Notification error - $e");
    }
    
    // Callback for in-app handling
    onAlert?.call(alert);
    notifyListeners();
  }

  /// Parse time string to DateTime components
  DateTime _parseTime(String time) {
    final parts = time.split(':');
    return DateTime(2000, 1, 1, int.parse(parts[0]), int.parse(parts[1]));
  }

  @override
  void dispose() {
    stopPatrol();
    super.dispose();
  }
}
